name = "MacroEnergyTimeReduction"
uuid = "f4afba0d-ee76-4f0d-9e6b-7521d0ede300"
authors = ["Jun Wen Law <junlaw@mit.edu>", "Louis Cui <>", "Ruaridh Macdonald <rmacd@mit.edu>", "Dharik Mallapragada <dharik@mit.edu>"]
version = "0.0.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1"
Clustering = "0.15"
DataFrames = "1"
Distances = "0.10"
Flux = "0.16"
LinearAlgebra = "1"
Random = "1"
StatsBase = "0.34"
Zygote = "0.7"


